#!/usr/bin/env bash
# Regenerate PATCHES.md from the commits carried on top of the upstream base tag.
#
# No commit hashes: they change on every rebase, and the commit that carries this file cannot know
# its own. Rows are the commit subjects, in series order; `git log <base>..nexus/main` gives the hashes.
#
# The register is derived from git, never edited by hand: each carried commit must end with an
# Upstream-Status trailer (Pending | Submitted [url] | Backport [#pr] | Denied | Inappropriate [reason]),
# and this script refuses to write the file if one is missing or malformed. The release workflow runs
# it and fails if the checked-in PATCHES.md is stale.
#
# Usage: nexus/gen-patches.sh [base]   (default: the merge base with the develop mirror, which is
# the upstream commit the series sits on; a release tag when the series is on a release)
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

upstream=https://github.com/FirelyTeam/firely-cql-sdk
# The develop mirror is upstream's develop as last fetched into this repository.
mirror=$(git rev-parse -q --verify origin/develop || git rev-parse -q --verify develop || true)
base=${1:-$(git merge-base HEAD "$mirror")}
base_sha=$(git rev-parse --short=8 "$base^{commit}")
# Name the base by its release tag when it has one, otherwise by the commit on develop.
base_tag=$(git describe --tags --exact-match --match 'v[0-9]*' --exclude '*-nexus.*' "$base" 2>/dev/null || true)
if [ -n "$base_tag" ]; then
  base_label="[$base_tag]($upstream/releases/tag/$base_tag) (\`$base_sha\`)"
else
  base_label="develop at [\`$base_sha\`]($upstream/commit/$base_sha)"
fi
# The last release at or before the base, for the list of what merged upstream since it.
last_tag=$(git describe --tags --abbrev=0 --match 'v[0-9]*' --exclude '*-nexus.*' "$base" 2>/dev/null || true)
commits=$(git rev-list --reverse "$base..HEAD")
count=$(printf '%s\n' "$commits" | grep -c . || true)

status_re='^(Pending|Submitted \[[^]]+\]|Backport \[[^]]+\]|Denied|Inappropriate \[[^]]+\])$'

# This repository's web URL, for linking a row to its pull-request branch. From origin, which in
# the release workflow and in any clone of the fork is this repository.
origin_url=$(git remote get-url origin 2>/dev/null | sed -E 's#^git@github\.com:#https://github.com/#; s#\.git$##')

# The branch a fix is staged on for its upstream pull request: the nexus/fix-* branch (local
# or on origin) that carries a commit with the same subject. Derived rather than recorded in
# the commit, so the commits that go upstream carry nothing about our branch layout.
# Only the commits a branch ADDS over the develop mirror count: the mirror itself contains
# upstream's own commits, including anything we carry as a Backport, and those must not link.
mirror=$(git rev-parse -q --verify origin/develop || git rev-parse -q --verify develop || true)
# A branch may stack on another (one fix depends on an earlier one), so several branches can
# carry the same subject; the smallest one is the branch that IS that fix.
branch_for() {
  local subject=$1 ref n best= best_n=
  [ -n "$mirror" ] || return 0
  for ref in $(git for-each-ref --format='%(refname:short)' 'refs/heads/nexus/fix-*' 'refs/remotes/origin/nexus/fix-*'); do
    # Not grep -q: under pipefail an early exit hands git log a SIGPIPE and the match is lost.
    if [ -n "$(git log --format=%s "$mirror..$ref" | grep -xF -- "$subject" || true)" ]; then
      n=$(git rev-list --count "$mirror..$ref")
      if [ -z "$best_n" ] || [ "$n" -lt "$best_n" ]; then best=${ref#origin/}; best_n=$n; fi
    fi
  done
  printf '%s' "$best"
}
{
  echo "# Patches carried by the Nexus EMR fork"
  echo
  echo "Base: $base_label of [FirelyTeam/firely-cql-sdk]($upstream)."
  echo "Carried: $count commits. Generated by \`nexus/gen-patches.sh\` from the \`Upstream-Status\` trailers; do not edit by hand."
  echo
  echo "Every fix is sent upstream. A row leaves this table when its upstream pull request is merged and the series is rebased onto a base that contains it."
  # Fixes from this fork that upstream has merged since the last release: derived from the merge
  # commits on the base's history, so the register still names them after their rows have left.
  if [ -n "$last_tag" ] && [ "$(git rev-parse "$last_tag^{commit}")" != "$(git rev-parse "$base^{commit}")" ]; then
    merged=$(git log --merges --format='%H' "$last_tag..$base" --grep '^Merge pull request #[0-9]* from AwareMD/')
    if [ -n "$merged" ]; then
      echo
      echo "Merged upstream since [$last_tag]($upstream/releases/tag/$last_tag) and no longer carried:"
      echo
      for m in $merged; do
        pr=$(git log -1 --format='%s' "$m" | sed -E 's|^Merge pull request #([0-9]+) .*|\1|')
        # GitHub writes the pull request title as the body of its merge commit.
        title=$(git log -1 --format='%b' "$m" | sed '/^$/d' | head -1)
        echo "- [#$pr]($upstream/pull/$pr) $title"
      done
    fi
  fi
  echo
  echo "| # | subject | branch | upstream status |"
  echo "|---|---|---|---|"
  n=0
  for c in $commits; do
    n=$((n + 1))
    subject=$(git log -1 --format=%s "$c")
    status=$(git log -1 --format='%(trailers:key=Upstream-Status,valueonly)' "$c" | sed '/^$/d' | head -1)
    if [ -z "$status" ]; then
      echo "error: $c ($subject) has no Upstream-Status trailer" >&2; exit 1
    fi
    if ! printf '%s' "$status" | grep -Eq "$status_re"; then
      echo "error: $c ($subject) has a malformed Upstream-Status: '$status'" >&2; exit 1
    fi
    # [#1234] becomes a link to the upstream pull request
    status=$(printf '%s' "$status" | sed -E "s|\[#([0-9]+)\]|[#\1]($upstream/pull/\1)|g")
    branch=$(branch_for "$subject")
    if [ -n "$branch" ] && [ -n "$origin_url" ]; then branch="[\`$branch\`]($origin_url/tree/$branch)"; fi
    # An Upstream-Issue trailer names the issue the pull request closes
    issue=$(git log -1 --format='%(trailers:key=Upstream-Issue,valueonly)' "$c" | sed '/^$/d' | head -1)
    if [ -n "$issue" ]; then status="$status, issue [$issue]($upstream/issues/${issue#\#})"; fi
    echo "| $n | $subject | $branch | $status |"
  done
} > PATCHES.md
echo "PATCHES.md: $count commits on $base"
